#!/usr/bin/env python

# smart screen cli

URL="http://raspberrypi.local:1133"

import argparse
import requests
import urllib.parse

parser = argparse.ArgumentParser()
subparser = parser.add_subparsers(dest='command')

parser_url = subparser.add_parser('url', help='url')
parser_url.add_argument('-u', '--url', help='go to url')

parser_slideshow = subparser.add_parser('slideshow', help='slideshow')
parser_slideshow.add_argument('-s', '--start',  action='store_true' , help='start slideshow')

parser_misc = subparser.add_parser('misc', help='misc commands')
parser_misc.add_argument('-p', '--gitpull', action='store_true', help='git pull')

args = parser.parse_args()

if args.command == 'misc':
    if args.gitpull:
        requests.get("{}/git-pull".format(URL))

if args.command == 'slideshow':
    if args.start:
        requests.get("{}/slideshow/activate".format(URL))

if args.command == 'url':
    if args.url:
        url = urllib.parse.quote_plus(args.url)
        requests.post("{}/url".format(URL), data = {'url': url} )
